## Heart Disease Detection Based On DataSet Provided

In [1]:
import pandas as pd
import numpy as np

In [2]:
heart = pd.read_csv("heartdata.csv")

In [3]:
heartcopy = heart.copy()
heartcopy

Age  Sex  cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  num
0     28    1   2     130.0  132.0  0.0      2.0    185.0    0.0      0.0    0
1     29    1   2     120.0  243.0  0.0      0.0    160.0    0.0      0.0    0
2     29    1   2     140.0    NaN  0.0      0.0    170.0    0.0      0.0    0
3     30    0   1     170.0  237.0  0.0      1.0    170.0    0.0      0.0    0
4     31    0   2     100.0  219.0  0.0      1.0    150.0    0.0      0.0    0
..   ...  ...  ..       ...    ...  ...      ...      ...    ...      ...  ...
452   62    1   4     158.0  170.0  0.0      1.0    138.0    1.0      0.0    1
453   54    0   4     127.0  333.0  1.0      1.0    154.0    0.0      0.0    1
454   62    1   1       NaN  139.0  0.0      1.0      NaN    NaN      NaN    0
455   58    1   4       NaN  385.0  1.0      2.0      NaN    NaN      NaN    0
456   62    1   2     120.0  254.0  0.0      2.0     93.0    1.0      0.0    1

[457 rows x 11 columns]

In [4]:
heartcopy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       457 non-null    int64  
 1   Sex       457 non-null    int64  
 2   cp        457 non-null    int64  
 3   trestbps  424 non-null    float64
 4   chol      431 non-null    float64
 5   fbs       403 non-null    float64
 6   restecg   455 non-null    float64
 7   thalach   424 non-null    float64
 8   exang     424 non-null    float64
 9   oldpeak   421 non-null    float64
 10  num       457 non-null    int64  
dtypes: float64(7), int64(4)
memory usage: 39.4 KB


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = "median")
imputer.fit(heartcopy)

SimpleImputer(add_indicator=False, copy=True, fill_value=None,
              missing_values=nan, strategy='median', verbose=0)

In [6]:
X = imputer.transform(heartcopy)

In [7]:
heartcopy_tr = pd.DataFrame(X, columns = heartcopy.columns)

In [8]:
heartcopy_tr.describe()

Age         Sex          cp    trestbps        chol         fbs  \
count  457.000000  457.000000  457.000000  457.000000  457.000000  457.000000   
mean    50.962801    0.796499    3.155361  131.380744  201.183807    0.122538   
std      9.219588    0.403043    0.943548   18.139430  110.278700    0.328266   
min     28.000000    0.000000    1.000000   80.000000    0.000000    0.000000   
25%     45.000000    1.000000    2.000000  120.000000  179.000000    0.000000   
50%     52.000000    1.000000    3.000000  130.000000  220.000000    0.000000   
75%     57.000000    1.000000    4.000000  140.000000  266.000000    0.000000   
max     75.000000    1.000000    4.000000  200.000000  603.000000    1.000000   

          restecg     thalach       exang     oldpeak         num  
count  457.000000  457.000000  457.000000  457.000000  457.000000  
mean     0.354486  134.916849    0.332604    0.573085    0.459519  
std      0.589702   23.357201    0.471662    0.900729    0.498905  
min      0.000000   69.000000    0.000000   -2.600000    0.000000  
25%      0.000000  120.000000    0.000000    0.000000    0.000000  
50%      0.000000  135.000000    0.000000    0.000000    0.000000  
75%      1.000000  150.000000    1.000000    1.000000    1.000000  
max      2.000000  190.000000    1.000000    5.000000    1.000000

In [9]:
heartcopy_tr

Age  Sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0    28.0  1.0  2.0     130.0  132.0  0.0      2.0    185.0    0.0      0.0   
1    29.0  1.0  2.0     120.0  243.0  0.0      0.0    160.0    0.0      0.0   
2    29.0  1.0  2.0     140.0  220.0  0.0      0.0    170.0    0.0      0.0   
3    30.0  0.0  1.0     170.0  237.0  0.0      1.0    170.0    0.0      0.0   
4    31.0  0.0  2.0     100.0  219.0  0.0      1.0    150.0    0.0      0.0   
..    ...  ...  ...       ...    ...  ...      ...      ...    ...      ...   
452  62.0  1.0  4.0     158.0  170.0  0.0      1.0    138.0    1.0      0.0   
453  54.0  0.0  4.0     127.0  333.0  1.0      1.0    154.0    0.0      0.0   
454  62.0  1.0  1.0     130.0  139.0  0.0      1.0    135.0    0.0      0.0   
455  58.0  1.0  4.0     130.0  385.0  1.0      2.0    135.0    0.0      0.0   
456  62.0  1.0  2.0     120.0  254.0  0.0      2.0     93.0    1.0      0.0   

     num  
0    0.0  
1    0.0  
2    0.0  
3    0.0  
4    0.0  
..   ...  
452  1.0  
453  1.0  
454  0.0  
455  0.0  
456  1.0  

[457 rows x 11 columns]

In [10]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(heartcopy_tr, test_size = 0.2, random_state = 42)
print(len(train_set))
print(len(test_set))

365
92


In [11]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits = 1, test_size = 0.2, random_state = 42)
for train_index, test_index in split.split(heartcopy_tr['exang'], heartcopy_tr['Sex'], heartcopy_tr['num']):
    strat_train_set = heartcopy_tr.loc[train_index]
    strat_test_set = heartcopy_tr.loc[test_index]

In [12]:
strat_train_set["Sex"].value_counts()

1.0    291
0.0     74
Name: Sex, dtype: int64

In [13]:
strat_test_set["Sex"].value_counts()

1.0    73
0.0    19
Name: Sex, dtype: int64

In [14]:
291/74 

3.9324324324324325

In [15]:
73/19

3.8421052631578947

In [16]:
strat_train_set.describe()

Age         Sex          cp    trestbps        chol         fbs  \
count  365.000000  365.000000  365.000000  365.000000  365.000000  365.000000   
mean    51.208219    0.797260    3.123288  130.726027  203.671233    0.139726   
std      9.224635    0.402592    0.954245   17.533218  106.827201    0.347178   
min     28.000000    0.000000    1.000000   80.000000    0.000000    0.000000   
25%     45.000000    1.000000    2.000000  120.000000  181.000000    0.000000   
50%     52.000000    1.000000    3.000000  130.000000  220.000000    0.000000   
75%     58.000000    1.000000    4.000000  140.000000  264.000000    0.000000   
max     75.000000    1.000000    4.000000  190.000000  603.000000    1.000000   

          restecg     thalach       exang     oldpeak         num  
count  365.000000  365.000000  365.000000  365.000000  365.000000  
mean     0.361644  134.542466    0.334247    0.596438    0.446575  
std      0.593608   23.322429    0.472374    0.898634    0.497820  
min      0.000000   69.000000    0.000000   -1.500000    0.000000  
25%      0.000000  119.000000    0.000000    0.000000    0.000000  
50%      0.000000  135.000000    0.000000    0.000000    0.000000  
75%      1.000000  150.000000    1.000000    1.000000    1.000000  
max      2.000000  190.000000    1.000000    5.000000    1.000000

In [17]:
strat_test_set.describe()

Age        Sex         cp    trestbps        chol        fbs  \
count  92.000000  92.000000  92.000000   92.000000   92.000000  92.000000   
mean   49.989130   0.793478   3.282609  133.978261  191.315217   0.054348   
std     9.184907   0.407027   0.893519   20.263635  123.162979   0.227945   
min    31.000000   0.000000   1.000000   95.000000    0.000000   0.000000   
25%    43.000000   1.000000   2.750000  120.000000  117.000000   0.000000   
50%    50.500000   1.000000   4.000000  130.000000  220.000000   0.000000   
75%    55.250000   1.000000   4.000000  150.000000  273.250000   0.000000   
max    73.000000   1.000000   4.000000  200.000000  466.000000   1.000000   

         restecg     thalach      exang    oldpeak        num  
count  92.000000   92.000000  92.000000  92.000000  92.000000  
mean    0.326087  136.402174   0.326087   0.480435   0.510870  
std     0.576246   23.563830   0.471348   0.907991   0.502621  
min     0.000000   82.000000   0.000000  -2.600000   0.000000  
25%     0.000000  123.500000   0.000000   0.000000   0.000000  
50%     0.000000  135.500000   0.000000   0.000000   1.000000  
75%     1.000000  152.500000   1.000000   1.000000   1.000000  
max     2.000000  180.000000   1.000000   3.000000   1.000000

In [18]:
hr = strat_train_set.copy()

In [19]:
heart_num = strat_train_set.drop("num",axis = 1)
heart_num_labels = strat_train_set["num"].copy()

## Creating a Pipeline

In [20]:
from sklearn.pipeline import Pipeline
# from sklearn.preprocessing import StandardScaler
my_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
])

In [21]:
heart_num_jr = my_pipeline.fit_transform(heart_num)

In [22]:
heart_num_jr[0]

array([ 38. ,   1. ,   4. , 110. , 289. ,   0. ,   0. , 105. ,   1. ,
         1.5])

## Choosing the Best Model for Detection

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
# model = LogisticRegression()
# model = DecisionTreeClassifier()
model.fit(heart_num_jr, heart_num_labels)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [24]:
some_data = heart_num.iloc[:4]
some_labels = heart_num_labels.iloc[:4]

In [25]:
prepared_data = my_pipeline.transform(some_data)

In [26]:
model.predict(prepared_data)

array([1., 0., 0., 0.])

In [27]:
list(some_labels)

[1.0, 0.0, 0.0, 0.0]

## Evaluatig The model using Cross Validation

In [28]:
from sklearn.model_selection import cross_val_score

In [29]:
scores = cross_val_score(model, heart_num_jr, heart_num_labels, scoring = "neg_mean_squared_error", cv = 10)
rmse = np.sqrt(-scores)

In [30]:
rmse

array([0.63671454, 0.36760731, 0.46499055, 0.46499055, 0.63671454,
       0.52704628, 0.33333333, 0.66666667, 0.40824829, 0.47140452])

In [31]:
def print_value(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Standard Deviation:", scores.std())

In [32]:
print_value(rmse)

Scores: [0.63671454 0.36760731 0.46499055 0.46499055 0.63671454 0.52704628
 0.33333333 0.66666667 0.40824829 0.47140452]
Mean: 0.4977716588881109
Standard Deviation: 0.11083066212848407


## Joblib Dump

In [33]:
from joblib import dump,load

In [34]:
dump(model, "Heart.joblib")

['Heart.joblib']

In [35]:
prepared_data

array([[ 38. ,   1. ,   4. , 110. , 289. ,   0. ,   0. , 105. ,   1. ,
          1.5],
       [ 62. ,   1. ,   3. , 120. , 220. ,   0. ,   2. ,  86. ,   0. ,
          0. ],
       [ 50. ,   0. ,   4. , 120. , 328. ,   0. ,   0. , 110. ,   1. ,
          1. ],
       [ 44. ,   1. ,   2. , 120. , 184. ,   0. ,   0. , 142. ,   0. ,
          1. ]])

In [36]:
from sklearn.metrics import accuracy_score
true = model.predict(prepared_data)
prediction = list(some_labels)

In [37]:
Percentage_accuracy = str(accuracy_score(prediction, true, normalize = True)*100)
Percentage = Percentage_accuracy+"%"
Percentage

'100.0%'